//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaccaratBetLog
    {
        public long Id { get; set; }
        public long BaccaratGameId { get; set; }
        public int MemberId { get; set; }
        public decimal BankerBet { get; set; }
        public decimal PlayerBet { get; set; }
        public decimal TieBet { get; set; }
        public decimal BankerPairBet { get; set; }
        public decimal PlayerPairBet { get; set; }
        public decimal BankerWin { get; set; }
        public decimal PlayerWin { get; set; }
        public decimal TieWin { get; set; }
        public decimal BankerPairWin { get; set; }
        public decimal PlayerPairWin { get; set; }
        public decimal GoldCoinBet { get; set; }
        public decimal FreeCoinBet { get; set; }
        public decimal GoldCoinWin { get; set; }
        public decimal FreeCoinWin { get; set; }
        public decimal TotalBet { get; set; }
        public decimal TotalWin { get; set; }
        public decimal OutcomeAmount { get; set; }
        public RakeType RakeType { get; set; }
        public byte RakeRatio { get; set; }
        public decimal RakeAmount { get; set; }
        public decimal RakeResult { get; set; }
        public decimal ResultAmount { get; set; }
        public decimal GoldCoinBudget { get; set; }
        public decimal FreeCoinBudget { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual BaccaratGame BaccaratGame { get; set; }
        public virtual Member Member { get; set; }
    }
}
