//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaccaratGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaccaratGame()
        {
            this.BaccaratBetLog = new HashSet<BaccaratBetLog>();
        }
    
        public long Id { get; set; }
        public int TableId { get; set; }
        public int ShoeNumber { get; set; }
        public int GameNumber { get; set; }
        public string BankerFirstCard { get; set; }
        public string BankerSecondCard { get; set; }
        public string BankerThirdCard { get; set; }
        public string PlayerFirstCard { get; set; }
        public string PlayerSecondCard { get; set; }
        public string PlayerThirdCard { get; set; }
        public string RoadTip { get; set; }
        public bool IsBankerWin { get; set; }
        public bool IsPlayerWin { get; set; }
        public bool IsTieWin { get; set; }
        public bool IsBankerPairWin { get; set; }
        public bool IsPlayerPairWin { get; set; }
        public bool IsResult { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaccaratBetLog> BaccaratBetLog { get; set; }
        public virtual Table Table { get; set; }
    }
}
