//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaccaratBetLimit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaccaratBetLimit()
        {
            this.MemberBaccaratConfig = new HashSet<MemberBaccaratConfig>();
        }
    
        public int Id { get; set; }
        public decimal SingleUpperLimit { get; set; }
        public decimal SingleLowerLimit { get; set; }
        public decimal PairUpperLimit { get; set; }
        public decimal PairLowerLimit { get; set; }
        public decimal TieUpperLimit { get; set; }
        public decimal TieLowerLimit { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberBaccaratConfig> MemberBaccaratConfig { get; set; }
    }
}
