//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DouDizhuGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DouDizhuGame()
        {
            this.DouDizhuBet = new HashSet<DouDizhuBet>();
        }
    
        public long Id { get; set; }
        public int GameId { get; set; }
        public string SerialNumber { get; set; }
        public int BaseValue { get; set; }
        public bool SnatchLord { get; set; }
        public bool Fine { get; set; }
        public bool MissionMode { get; set; }
        public int LordPlayerId { get; set; }
        public string MissionType { get; set; }
        public int CallMultiplier { get; set; }
        public int FinalMultiplier { get; set; }
        public int NumOfSpring { get; set; }
        public int NumOfAntiSpring { get; set; }
        public int NumOfBomb { get; set; }
        public int NumOfRocket { get; set; }
        public bool MissionAccomplished { get; set; }
        public string GameLog { get; set; }
        public bool IsResult { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DouDizhuBet> DouDizhuBet { get; set; }
        public virtual Game Game { get; set; }
        public virtual Member Member { get; set; }
    }
}
