//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.JackpotLog = new HashSet<JackpotLog>();
            this.Wallet = new HashSet<Wallet>();
            this.Table = new HashSet<Table>();
            this.TwMahjongGame = new HashSet<TwMahjongGame>();
            this.DouDizhuGame = new HashSet<DouDizhuGame>();
            this.TexasGame = new HashSet<TexasGame>();
            this.GdMahjongGame = new HashSet<GdMahjongGame>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
        public string FileToken { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string ServerUrl { get; set; }
        public int ServerPort { get; set; }
        public string ServerRest { get; set; }
        public string ServerUrlForFun { get; set; }
        public int ServerPortForFun { get; set; }
        public string ServerRestForFun { get; set; }
        public bool Jackpot { get; set; }
        public int Click { get; set; }
        public int Sort { get; set; }
        public GameCategory Category { get; set; }
        public GameStatus Status { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JackpotLog> JackpotLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table> Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TwMahjongGame> TwMahjongGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DouDizhuGame> DouDizhuGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TexasGame> TexasGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GdMahjongGame> GdMahjongGame { get; set; }
    }
}
