//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GdMahjongConfig
    {
        public int Id { get; set; }
        public int Antes { get; set; }
        public int Tai { get; set; }
        public MahjongConfigRoundType RoundType { get; set; }
        public int ThinkTime { get; set; }
        public int ServiceCharge { get; set; }
        public int MoneyLimit { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
