//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JackpotLog
    {
        public long Id { get; set; }
        public int PlayerId { get; set; }
        public int GameId { get; set; }
        public string JackpotType { get; set; }
        public decimal Jackpot { get; set; }
        public int Base { get; set; }
        public decimal Ratio { get; set; }
        public decimal WinAmount { get; set; }
        public decimal BaseAmount { get; set; }
        public decimal FillAmount { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Member Member { get; set; }
    }
}
