//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    
    public enum MemberRole : byte
    {
        Root = 255,
        Admin = 254,
        Vendor = 0,
        Webmaster = 1,
        Agent = 2,
        Subagent = 3,
        Player = 4,
        Robot = 5
    }
}
