//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouletteBetLimit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouletteBetLimit()
        {
            this.MemberRouletteConfig = new HashSet<MemberRouletteConfig>();
        }
    
        public int Id { get; set; }
        public decimal UpperLimit1x35 { get; set; }
        public decimal LowerLimit1x35 { get; set; }
        public decimal UpperLimit1x17_1x11 { get; set; }
        public decimal LowerLimit1x17_1x11 { get; set; }
        public decimal UpperLimit1x8_1x5 { get; set; }
        public decimal LowerLimit1x8_1x5 { get; set; }
        public decimal UpperLimit1x2_1x1 { get; set; }
        public decimal LowerLimit1x2_1x1 { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberRouletteConfig> MemberRouletteConfig { get; set; }
    }
}
