//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SicboGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SicboGame()
        {
            this.SicboBetLog = new HashSet<SicboBetLog>();
        }
    
        public long Id { get; set; }
        public int TableId { get; set; }
        public int ShoeNumber { get; set; }
        public int GameNumber { get; set; }
        public Nullable<int> Dice_1 { get; set; }
        public Nullable<int> Dice_2 { get; set; }
        public Nullable<int> Dice_3 { get; set; }
        public string RoadTip { get; set; }
        public bool IsBigWin { get; set; }
        public bool IsSmallWin { get; set; }
        public bool IsOddWin { get; set; }
        public bool IsEvenWin { get; set; }
        public bool IsResult { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SicboBetLog> SicboBetLog { get; set; }
        public virtual Table Table { get; set; }
    }
}
