//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TexasGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TexasGame()
        {
            this.TexasBet = new HashSet<TexasBet>();
        }
    
        public long Id { get; set; }
        public int GameId { get; set; }
        public string SerialNumber { get; set; }
        public int DealerSeat { get; set; }
        public int SmallBlind { get; set; }
        public int BigBlind { get; set; }
        public string Cards { get; set; }
        public byte TotalPlayer { get; set; }
        public byte ActivePlayer { get; set; }
        public string GameLog { get; set; }
        public bool IsResult { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TexasBet> TexasBet { get; set; }
    }
}
