//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TexasBet
    {
        public long Id { get; set; }
        public long TexasGameId { get; set; }
        public int PlayerId { get; set; }
        public int Seat { get; set; }
        public string FirstCard { get; set; }
        public string SecondCard { get; set; }
        public string Bets { get; set; }
        public string Results { get; set; }
        public decimal Fee { get; set; }
        public decimal BetAmount { get; set; }
        public decimal WinAmount { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime InsertDate { get; set; }
        public byte[] WinType { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual TexasGame TexasGame { get; set; }
    }
}
