//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameEnable
    {
        public int SID { get; set; }
        public string Game { get; set; }
        public string GameType { get; set; }
        public int Status { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public int Level { get; set; }
    }
}
