//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pc_Keno_Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pc_Keno_Sample()
        {
            this.BallSmall = "{\"Enable\":1,\"Name\":\"小\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":2,\"BetMa" +
        "x\":500,\"SingelMax\":5000,\"DishMax\":12345}";
            this.BallMid = "{\"Enable\":1,\"Name\":\"中\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":2,\"BetMa" +
        "x\":500,\"SingelMax\":5000,\"DishMax\":12345}";
            this.BallBig = "{\"Enable\":1,\"Name\":\"大\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":500,\"SingelMax\":5000,\"DishMax\":12345}";
            this.BallOdd = "{\"Enable\":1,\"Name\":\"奇\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.BallSam = "{\"Enable\":1,\"Name\":\"和\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.BallEven = "{\"Enable\":1,\"Name\":\"偶\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumBig = "{\"Enable\":1,\"Name\":\"總和大\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"Bet" +
        "Max\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumSmall = "{\"Enable\":1,\"Name\":\"小\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumOdd = "{\"Enable\":1,\"Name\":\"單\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumEven = "{\"Enable\":1,\"Name\":\"雙\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumBigOdd = "{\"Enable\":0,\"Name\":\"大單\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetM" +
        "ax\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumSmallOdd = "{\"Enable\":0,\"Name\":\"小單\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":0,\"BetM" +
        "ax\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumBigEven = "{\"Enable\":0,\"Name\":\"大雙\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":0,\"BetM" +
        "ax\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.SumSmallEven = "{\"Enable\":0,\"Name\":\"小雙\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":0,\"BetM" +
        "ax\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.Range_1 = "{\"Enable\":0,\"Name\":\"金\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.Range_2 = "{\"Enable\":0,\"Name\":\"木\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.Range_3 = "{\"Enable\":0,\"Name\":\"水\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.Range_4 = "{\"Enable\":0,\"Name\":\"火\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.Range_5 = "{\"Enable\":0,\"Name\":\"土\",\"Odds\":1.97,\"Water\":1.1,\"WaterBack\":0.05,\"BetMin\":1,\"BetMa" +
        "x\":1,\"SingelMax\":5000,\"DishMax\":10000}";
            this.BallMaxMonney = 100000;
        }
    
        public int SID { get; set; }
        public string UserID { get; set; }
        public string Location { get; set; }
        public string Dish { get; set; }
        public string BallSmall { get; set; }
        public string BallMid { get; set; }
        public string BallBig { get; set; }
        public string BallOdd { get; set; }
        public string BallSam { get; set; }
        public string BallEven { get; set; }
        public string SumBig { get; set; }
        public string SumSmall { get; set; }
        public string SumOdd { get; set; }
        public string SumEven { get; set; }
        public string SumBigOdd { get; set; }
        public string SumSmallOdd { get; set; }
        public string SumBigEven { get; set; }
        public string SumSmallEven { get; set; }
        public string Range_1 { get; set; }
        public string Range_2 { get; set; }
        public string Range_3 { get; set; }
        public string Range_4 { get; set; }
        public string Range_5 { get; set; }
        public int BallMaxMonney { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public int CompanyID { get; set; }
    }
}
