//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameControl.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    
    public partial class URL
    {
        [DbImport]
        public int SID { get; set; }
        [DbImport]
        public string GameType { get; set; }
        [DbImport]
        public string Location { get; set; }
        [DbImport]
        public string Url1 { get; set; }
        [DbImport]
        public int Status { get; set; }
        [DbImport]
        public int Sort { get; set; }
        [DbImport]
        public System.DateTime UpdateTime { get; set; }
        [DbImport]
        public string UpdateUser { get; set; }
        [DbImport]
        public int LoadTime { get; set; }
        [DbImport]
        public int FailCount { get; set; }
    }
}
