CREATE TABLE [dbo].[UserID] (
    [I] INT              IDENTITY (2, 1) NOT NULL,
    [U] UNIQUEIDENTIFIER NOT NULL,
    [T] TINYINT          NOT NULL,
    [A] VARCHAR (20)     NOT NULL,
    CONSTRAINT [PK_UserID] PRIMARY KEY CLUSTERED ([I] ASC),
    CONSTRAINT [IX_UserID] UNIQUE NONCLUSTERED ([U] ASC)
);

