CREATE TABLE [dbo].[TranID2] (
    [SN]     INT              IDENTITY (1, 1) NOT NULL,
    [ID]     UNIQUEIDENTIFIER NOT NULL,
    [prefix] VARCHAR (10)     NOT NULL,
    CONSTRAINT [PK_TranID2] PRIMARY KEY CLUSTERED ([SN] ASC),
    CONSTRAINT [IX_TranID2] UNIQUE NONCLUSTERED ([ID] ASC)
);



