CREATE TABLE [dbo].[TranID3] (
    [SN]     INT              IDENTITY (1, 1) NOT NULL,
    [ID]     UNIQUEIDENTIFIER NOT NULL,
    [prefix] VARCHAR (10)     NOT NULL,
    CONSTRAINT [PK_TranID3] PRIMARY KEY CLUSTERED ([SN] ASC),
    CONSTRAINT [IX_TranID3] UNIQUE NONCLUSTERED ([ID] ASC)
);



