//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Lobby.TG.Resources
{


    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IG.Lobby.TG.Resources.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Ante 的當地語系化字串。
        /// </summary>
        internal static string Ante {
            get {
                return ResourceManager.GetString("Ante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ante / Tai 的當地語系化字串。
        /// </summary>
        internal static string AnteTai {
            get {
                return ResourceManager.GetString("AnteTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Countdown 的當地語系化字串。
        /// </summary>
        internal static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dou Dizhu 的當地語系化字串。
        /// </summary>
        internal static string GameName_DOUDIZHUVIDEO {
            get {
                return ResourceManager.GetString("GameName_DOUDIZHUVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Guangdong Mahjong 的當地語系化字串。
        /// </summary>
        internal static string GameName_GDMAHJONGVIDEO {
            get {
                return ResourceManager.GetString("GameName_GDMAHJONGVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Texas Hold &apos;em 的當地語系化字串。
        /// </summary>
        internal static string GameName_TEXASHOLDEMVIDEO {
            get {
                return ResourceManager.GetString("GameName_TEXASHOLDEMVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taiwan Mahjong 的當地語系化字串。
        /// </summary>
        internal static string GameName_TWMAHJONGVIDEO {
            get {
                return ResourceManager.GetString("GameName_TWMAHJONGVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Four Round 的當地語系化字串。
        /// </summary>
        internal static string MahjongConfigRoundType_FourRound {
            get {
                return ResourceManager.GetString("MahjongConfigRoundType_FourRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 One Round 的當地語系化字串。
        /// </summary>
        internal static string MahjongConfigRoundType_OneRound {
            get {
                return ResourceManager.GetString("MahjongConfigRoundType_OneRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Buy In 的當地語系化字串。
        /// </summary>
        internal static string MaxMinBuyIn {
            get {
                return ResourceManager.GetString("MaxMinBuyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Min Buy In 的當地語系化字串。
        /// </summary>
        internal static string MinBuyIn {
            get {
                return ResourceManager.GetString("MinBuyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No. Players 的當地語系化字串。
        /// </summary>
        internal static string NumOfPlayer {
            get {
                return ResourceManager.GetString("NumOfPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No. Round 的當地語系化字串。
        /// </summary>
        internal static string NumOfRound {
            get {
                return ResourceManager.GetString("NumOfRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ok 的當地語系化字串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Play Game 的當地語系化字串。
        /// </summary>
        internal static string PlayGame {
            get {
                return ResourceManager.GetString("PlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sec. 的當地語系化字串。
        /// </summary>
        internal static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Blind 的當地語系化字串。
        /// </summary>
        internal static string SmallBigBlind {
            get {
                return ResourceManager.GetString("SmallBigBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System notification 的當地語系化字串。
        /// </summary>
        internal static string SystemNotification {
            get {
                return ResourceManager.GetString("SystemNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Table Name 的當地語系化字串。
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
