//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Lobby.VA.Resources
{


    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IG.Lobby.VA.Resources.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7PK Goblin 的當地語系化字串。
        /// </summary>
        internal static string GameName_7PKGOBLIN {
            get {
                return ResourceManager.GetString("GameName_7PKGOBLIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 7PK Ninja 的當地語系化字串。
        /// </summary>
        internal static string GameName_7PKNINJA {
            get {
                return ResourceManager.GetString("GameName_7PKNINJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 After School 的當地語系化字串。
        /// </summary>
        internal static string GameName_AFTERSCHOOL {
            get {
                return ResourceManager.GetString("GameName_AFTERSCHOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 After School (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_AFTERSCHOOL_S {
            get {
                return ResourceManager.GetString("GameName_AFTERSCHOOL_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ai Uehara 的當地語系化字串。
        /// </summary>
        internal static string GameName_AIUEHARA {
            get {
                return ResourceManager.GetString("GameName_AIUEHARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ai Uehara (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_AIUEHARA_S {
            get {
                return ResourceManager.GetString("GameName_AIUEHARA_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Astral Luck 的當地語系化字串。
        /// </summary>
        internal static string GameName_ASTRALLUCK {
            get {
                return ResourceManager.GetString("GameName_ASTRALLUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Atomic Age 的當地語系化字串。
        /// </summary>
        internal static string GameName_ATOMICTGE {
            get {
                return ResourceManager.GetString("GameName_ATOMICTGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Busty Babies 的當地語系化字串。
        /// </summary>
        internal static string GameName_AVBUSTYBABIES {
            get {
                return ResourceManager.GetString("GameName_AVBUSTYBABIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Busty Babies (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_AVBUSTYBABIES_S {
            get {
                return ResourceManager.GetString("GameName_AVBUSTYBABIES_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hatano Yui 的當地語系化字串。
        /// </summary>
        internal static string GameName_AVHATANOYUI {
            get {
                return ResourceManager.GetString("GameName_AVHATANOYUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hatano Yui (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_AVHATANOYUI_S {
            get {
                return ResourceManager.GetString("GameName_AVHATANOYUI_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Axe Gang 的當地語系化字串。
        /// </summary>
        internal static string GameName_AXEGANG {
            get {
                return ResourceManager.GetString("GameName_AXEGANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Beauty And The Nerd 的當地語系化字串。
        /// </summary>
        internal static string GameName_BEAUTYANDTHENERD {
            get {
                return ResourceManager.GetString("GameName_BEAUTYANDTHENERD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Best Of Luck 的當地語系化字串。
        /// </summary>
        internal static string GameName_BESTOFLUCK {
            get {
                return ResourceManager.GetString("GameName_BESTOFLUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bruce Lee 的當地語系化字串。
        /// </summary>
        internal static string GameName_BRUCELEE {
            get {
                return ResourceManager.GetString("GameName_BRUCELEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Candy Cottage 的當地語系化字串。
        /// </summary>
        internal static string GameName_CANDYCOTTAGE {
            get {
                return ResourceManager.GetString("GameName_CANDYCOTTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cars 的當地語系化字串。
        /// </summary>
        internal static string GameName_CARS {
            get {
                return ResourceManager.GetString("GameName_CARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cleopatra Coins 的當地語系化字串。
        /// </summary>
        internal static string GameName_CLEOPATRASCOINS {
            get {
                return ResourceManager.GetString("GameName_CLEOPATRASCOINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collector 的當地語系化字串。
        /// </summary>
        internal static string GameName_COLLECTOR {
            get {
                return ResourceManager.GetString("GameName_COLLECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Diamond Temple 的當地語系化字串。
        /// </summary>
        internal static string GameName_DIAMONDTEMPLE {
            get {
                return ResourceManager.GetString("GameName_DIAMONDTEMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dou Dizhu Slot 的當地語系化字串。
        /// </summary>
        internal static string GameName_DOUDIZHUSLOT {
            get {
                return ResourceManager.GetString("GameName_DOUDIZHUSLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dreams Come True 的當地語系化字串。
        /// </summary>
        internal static string GameName_DREAMSCOMETRUE {
            get {
                return ResourceManager.GetString("GameName_DREAMSCOMETRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dreams Come True (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_DREAMSCOMETRUE_S {
            get {
                return ResourceManager.GetString("GameName_DREAMSCOMETRUE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Flying Colors 的當地語系化字串。
        /// </summary>
        internal static string GameName_FLYINGCOLORS {
            get {
                return ResourceManager.GetString("GameName_FLYINGCOLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Goddess Of Nerds 的當地語系化字串。
        /// </summary>
        internal static string GameName_GODDESSOFNERDS {
            get {
                return ResourceManager.GetString("GameName_GODDESSOFNERDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Goddess Of Nerds (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_GODDESSOFNERDS_S {
            get {
                return ResourceManager.GetString("GameName_GODDESSOFNERDS_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Gushers Gold 的當地語系化字串。
        /// </summary>
        internal static string GameName_GUSHERSGOLD {
            get {
                return ResourceManager.GetString("GameName_GUSHERSGOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ice Picks 的當地語系化字串。
        /// </summary>
        internal static string GameName_ICEPICKS {
            get {
                return ResourceManager.GetString("GameName_ICEPICKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 King 5PK 的當地語系化字串。
        /// </summary>
        internal static string GameName_KING5PK {
            get {
                return ResourceManager.GetString("GameName_KING5PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lounge Bar 的當地語系化字串。
        /// </summary>
        internal static string GameName_LOUNGEBAR {
            get {
                return ResourceManager.GetString("GameName_LOUNGEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Magic 的當地語系化字串。
        /// </summary>
        internal static string GameName_MAGIC {
            get {
                return ResourceManager.GetString("GameName_MAGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mario Sisters 的當地語系化字串。
        /// </summary>
        internal static string GameName_MARIOSISTERS {
            get {
                return ResourceManager.GetString("GameName_MARIOSISTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Monster 的當地語系化字串。
        /// </summary>
        internal static string GameName_MONSTER {
            get {
                return ResourceManager.GetString("GameName_MONSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Secret Garden 的當地語系化字串。
        /// </summary>
        internal static string GameName_MYSECRETGARDEN {
            get {
                return ResourceManager.GetString("GameName_MYSECRETGARDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Secret Garden (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_MYSECRETGARDEN_S {
            get {
                return ResourceManager.GetString("GameName_MYSECRETGARDEN_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Night Of Shanghai 的當地語系化字串。
        /// </summary>
        internal static string GameName_NIGHTOFSHANGHAI {
            get {
                return ResourceManager.GetString("GameName_NIGHTOFSHANGHAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nuclear Fishin&apos; 的當地語系化字串。
        /// </summary>
        internal static string GameName_NUCLEARFISHIN {
            get {
                return ResourceManager.GetString("GameName_NUCLEARFISHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Oasis Poker Advance 的當地語系化字串。
        /// </summary>
        internal static string GameName_OASISPOKERADVANCE {
            get {
                return ResourceManager.GetString("GameName_OASISPOKERADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Oasis Poker Basic 的當地語系化字串。
        /// </summary>
        internal static string GameName_OASISPOKERBASIC {
            get {
                return ResourceManager.GetString("GameName_OASISPOKERBASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Oasis Poker Intermediate 的當地語系化字串。
        /// </summary>
        internal static string GameName_OASISPOKERINTERMEDIATE {
            get {
                return ResourceManager.GetString("GameName_OASISPOKERINTERMEDIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ocean Treasure 的當地語系化字串。
        /// </summary>
        internal static string GameName_OCEANTREASURE {
            get {
                return ResourceManager.GetString("GameName_OCEANTREASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opera Night 的當地語系化字串。
        /// </summary>
        internal static string GameName_OPERANIGHT {
            get {
                return ResourceManager.GetString("GameName_OPERANIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prehistoric Park 的當地語系化字串。
        /// </summary>
        internal static string GameName_PREHISTORICPARK {
            get {
                return ResourceManager.GetString("GameName_PREHISTORICPARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Racing Queen 的當地語系化字串。
        /// </summary>
        internal static string GameName_RACINGQUEEN {
            get {
                return ResourceManager.GetString("GameName_RACINGQUEEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Racing Queen (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_RACINGQUEEN_S {
            get {
                return ResourceManager.GetString("GameName_RACINGQUEEN_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Red Dog Poker Advance 的當地語系化字串。
        /// </summary>
        internal static string GameName_REDDOGPOKERADVANCE {
            get {
                return ResourceManager.GetString("GameName_REDDOGPOKERADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Red Dog Poker Basic 的當地語系化字串。
        /// </summary>
        internal static string GameName_REDDOGPOKERBASIC {
            get {
                return ResourceManager.GetString("GameName_REDDOGPOKERBASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Red Dog Poker Intermediate 的當地語系化字串。
        /// </summary>
        internal static string GameName_REDDOGPOKERINTERMEDIATE {
            get {
                return ResourceManager.GetString("GameName_REDDOGPOKERINTERMEDIATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reel Of Fortune 的當地語系化字串。
        /// </summary>
        internal static string GameName_REELOFFORTUNE {
            get {
                return ResourceManager.GetString("GameName_REELOFFORTUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rocket 的當地語系化字串。
        /// </summary>
        internal static string GameName_ROCKET {
            get {
                return ResourceManager.GetString("GameName_ROCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Roll Out The Barrels 的當地語系化字串。
        /// </summary>
        internal static string GameName_ROLLOUTTHEBARRELS {
            get {
                return ResourceManager.GetString("GameName_ROLLOUTTHEBARRELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scary Rich 的當地語系化字串。
        /// </summary>
        internal static string GameName_SCARYRICH {
            get {
                return ResourceManager.GetString("GameName_SCARYRICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Secret Garden 的當地語系化字串。
        /// </summary>
        internal static string GameName_SECRETGARDEN {
            get {
                return ResourceManager.GetString("GameName_SECRETGARDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Special Tutor 的當地語系化字串。
        /// </summary>
        internal static string GameName_SPECIALTUITION {
            get {
                return ResourceManager.GetString("GameName_SPECIALTUITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Special Tutor (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_SPECIALTUITION_S {
            get {
                return ResourceManager.GetString("GameName_SPECIALTUITION_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Star Teams 的當地語系化字串。
        /// </summary>
        internal static string GameName_STARTEAMS5PK {
            get {
                return ResourceManager.GetString("GameName_STARTEAMS5PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Summer Ease 的當地語系化字串。
        /// </summary>
        internal static string GameName_SUMMEREASE {
            get {
                return ResourceManager.GetString("GameName_SUMMEREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 True Illusions 的當地語系化字串。
        /// </summary>
        internal static string GameName_TRUEILLUSIONS {
            get {
                return ResourceManager.GetString("GameName_TRUEILLUSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Watch the birdie 的當地語系化字串。
        /// </summary>
        internal static string GameName_WATCHTHEBIRDIE {
            get {
                return ResourceManager.GetString("GameName_WATCHTHEBIRDIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Winter Wonders 的當地語系化字串。
        /// </summary>
        internal static string GameName_WINTERWONDERS {
            get {
                return ResourceManager.GetString("GameName_WINTERWONDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yoshizawa Akiho 的當地語系化字串。
        /// </summary>
        internal static string GameName_YOSHIZAWAAKIHO {
            get {
                return ResourceManager.GetString("GameName_YOSHIZAWAAKIHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yoshizawa Akiho (S) 的當地語系化字串。
        /// </summary>
        internal static string GameName_YOSHIZAWAAKIHO_S {
            get {
                return ResourceManager.GetString("GameName_YOSHIZAWAAKIHO_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Zombiezee Money 的當地語系化字串。
        /// </summary>
        internal static string GameName_ZOMBIEZEEMONEY {
            get {
                return ResourceManager.GetString("GameName_ZOMBIEZEEMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ok 的當地語系化字串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System notification 的當地語系化字串。
        /// </summary>
        internal static string SystemNotification {
            get {
                return ResourceManager.GetString("SystemNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;span&gt;{0}&lt;/span&gt; won jackpot &lt;span&gt;{2}&lt;/span&gt; at &lt;span&gt;{1}&lt;/span&gt; 的當地語系化字串。
        /// </summary>
        internal static string WinJackpot {
            get {
                return ResourceManager.GetString("WinJackpot", resourceCulture);
            }
        }
    }
}
